In [17]:
import numpy as np

def do_convolution_depthwise(image, kernel):
    """
    Perform depthwise convolution on an image with a given kernel.
    """
    k_height, k_width, _ = kernel.shape
    height, width, channels = image.shape
    
    # Output dimensions
    output_height = height - k_height + 1
    output_width = width - k_width + 1
    
    # Initialize the output
    output = np.zeros((output_height, output_width, channels))
    
    # Apply the kernel to each channel separately
    for c in range(channels):
        for i in range(output_height):
            for j in range(output_width):
                output[i, j, c] = np.sum(image[i:i+k_height, j:j+k_width, c] * kernel[:, :, c])
    
    return output

def do_convolution_pointwise(image, kernel):
    """
    Perform pointwise convolution on an image with a given kernel.
    """
    _, _, channels, out_channels = kernel.shape
    height, width, _ = image.shape
    
    # Initialize the output
    output = np.zeros((height, width, out_channels))
    
    # Apply the kernel across all channels
    for i in range(height):
        for j in range(width):
            for k in range(out_channels):
                output[i, j, k] = np.sum(image[i, j, :] * kernel[0, 0, :, k])
    
    return output

# Example of usage:
ip_image = np.random.rand(13, 13, 3)
depth_kernel = np.random.rand(3, 3, 3)
point_kernel = np.random.rand(1, 1, 3, 8)  #(3 input channels, 8 output channels)

# Perform convolutions based on an external flag
convolution_flag = 'depthwise'  # Change to 'pointwise' to perform pointwise convolution

if convolution_flag == 'depthwise':
    output = do_convolution_depthwise(ip_image, depth_kernel)
elif convolution_flag == 'pointwise':
    output = do_convolution_pointwise(ip_image, point_kernel)

print(output.shape)  
print(output)


(11, 11, 3)
[[[2.00170677 2.25919353 2.10835527]
  [2.57098003 2.24458181 2.18780678]
  [2.69254454 2.41045302 1.67046661]
  [2.81876897 2.09093648 2.27072197]
  [1.84784677 1.67715521 1.91315297]
  [2.61337935 1.83649742 1.4387628 ]
  [2.07692987 2.32313658 1.17634859]
  [1.9275964  2.27508162 1.25454771]
  [1.38979083 1.86651919 1.37099003]
  [1.86926474 2.00173193 1.46177647]
  [1.69790816 2.43305643 2.02212553]]

 [[2.30654678 1.74643757 2.00610963]
  [2.67125555 2.0832633  2.20780155]
  [2.48529883 2.40480268 1.79458956]
  [2.07847361 2.56805451 1.9177256 ]
  [2.11426287 2.56220196 1.50201285]
  [1.24173039 2.69417046 1.16183046]
  [1.74211883 3.04651722 1.14771824]
  [1.56266465 2.93682014 1.40977955]
  [2.02682969 2.26561689 2.28224103]
  [1.68203292 2.03147487 2.22123484]
  [2.29366244 2.70856255 2.50216586]]

 [[2.28487849 2.17056598 2.10658574]
  [2.78543322 2.33672998 2.18560519]
  [2.12804359 2.09444406 2.3319078 ]
  [2.23509416 2.4659789  1.78346144]
  [1.33357233 2.209937